### ISSUE TITLE
confusion over relationship between Load Balancer and Virtual Listener

### ISSUE THREAD

**Issue by jr2730** [DimensionDataResearch/ansible-dimensiondata#6]
It _SEEMS_ that VirtualListener "extends"/is-a-superset-of LoadBalancer.
After a bit of research, it seems more accurate to say that a Load Balancer is a simplified Virtual Listener.

If so, shouldn't there be some conversion back-and-forth?
Or is this not needed?

And if so, wouldn't that belong in the LoadBalancer/Driver?

@aimonb - I would appreciate a discussion on this.

**Comment by aimonb** [comment]
Load Balancer is a Node/Member, Pools, and Virtual Listeners. There is not actual Load Balancer object. So Node, Member and Pools are all subsets of the Load Balancer concept. In libcloud the "Load Balancer" is a quick and simplified way to create a Node, Pool and Virtual Listener, nothing more. By allowing a user to construct their own, we are allowing an advanced "Load Balancer" to be created.
