### ISSUE TITLE
Who is forking who?

### ISSUE THREAD

**Issue by jr2730** [DimensionDataResearch/ansible-dimensiondata#9]
Since it has now become clear (at least to ME) that:
- this repo should never be merged up into Ansible.*
- this repo exists to support OUR DD Ansible modules

It seems that this should be the PARENT and that it should not be a fork of anything else.
In other words, that DimensionDataDevOps (in this case) should somehow be removed as the parent of this repo.

@mikeoutland @aimonb

**Comment by aimonb** [comment]
@jr2730 @mikeoutland .. not sure how to do that. Perhaps delete the DimensionDataDevOps version.

**Comment by mikeoutland** [comment]
@SahajaKoorapati do you have permission to delete https://github.com/DimensionDataDevOps/ansible-dimensiondata ?

**Comment by relaxdiego** [comment]
Just deleted it. Now it points to @SahajaKoorapati's repo as the parent. Looks like you have to go to customer support to turn this into a parent.

**Comment by relaxdiego** [comment]
@mikeoutland @SahajaKoorapati @aimonb @jr2730 Another option is to pull the latest from this repo to your local machine, delete this repo, and then recreate it as a new empty repo. Finally, push your local clone to this repo. All existing issues and PRs will be deleted too, naturally.
